DROP TABLE IF EXISTS BOOKING ;

DROP TABLE IF EXISTS PET ;

DROP TABLE IF EXISTS EMPLOYEE ;

DROP TABLE IF EXISTS CLIENT ;

DROP TABLE IF EXISTS USERS ;

DROP TABLE IF EXISTS ACCOUNT ;

DROP TABLE IF EXISTS SEAT ;

DROP TABLE IF EXISTS ROOM ;

DROP TABLE IF EXISTS HOTEL ;