TRUNCATE TABLE ACCOUNT CASCADE;

TRUNCATE TABLE USERS CASCADE;

TRUNCATE TABLE HOTEL CASCADE;

TRUNCATE TABLE ROOM CASCADE;

TRUNCATE TABLE SEAT CASCADE;

TRUNCATE TABLE CLIENT CASCADE;

TRUNCATE TABLE PET CASCADE;

TRUNCATE TABLE EMPLOYEE CASCADE;

TRUNCATE TABLE BOOKING CASCADE;

TRUNCATE TABLE IMAGES CASCADE;