DROP TABLE IF EXISTS BOOKING CASCADE;

DROP TABLE IF EXISTS PET CASCADE;

DROP TABLE IF EXISTS EMPLOYEE CASCADE;

DROP TABLE IF EXISTS CLIENT CASCADE;

DROP TABLE IF EXISTS USERS CASCADE;

DROP TABLE IF EXISTS ACCOUNT CASCADE;

DROP TABLE IF EXISTS SEAT CASCADE;

DROP TABLE IF EXISTS ROOM CASCADE;

DROP TABLE IF EXISTS HOTEL CASCADE;

DROP TABLE IF EXISTS IMAGES CASCADE;

DROP TABLE IF EXISTS TOKENS CASCADE;