ALTER TABLE IF EXISTS PET DROP COLUMN FK_client_ID;

ALTER TABLE IF EXISTS BOOKING DROP COLUMN fk_employee_ID; 

DROP TABLE IF EXISTS EMPLOYEE;

DROP TABLE IF EXISTS HOTEL;

DROP TABLE IF EXISTS CLIENT;

DROP TABLE IF EXISTS BOOKING;

DROP TABLE IF EXISTS USERS;

DROP TABLE IF EXISTS PET;

DROP TABLE IF EXISTS ACCOUNT;

DROP TABLE IF EXISTS ROOM;

DROP TABLE IF EXISTS SEAT;