ALTER TABLE USERS
DROP COLUMN IF EXISTS password,
DROP COLUMN IF EXISTS role,
DROP COLUMN IF EXISTS verified,
DROP COLUMN IF EXISTS sex,
DROP COLUMN IF EXISTS photo,
ADD COLUMN IF NOT EXISTS account_id INTEGER REFERENCES ACCOUNT(id) ON DELETE CASCADE NOT NULL;

DROP TYPE IF EXISTS sex CASCADE;

DROP TYPE IF EXISTS user_type CASCADE;