version: '3.9'

services:
    goreact:
        build: ./
        command: ./wait-for-postgres.sh postgresql_database /main.go
        ports:
          - 8000:8000
        depends_on:
          - postgresql_database
        environment:
           - POSTGRES_USER=user
           - POSTGRES_PASSWORD=userpass
           - POSTGRES_DB=goreact

    postgresql_database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=changeme
            - POSTGRES_DB=goreact
        ports: 
            - "8081:5432"
        restart: always
        volumes: 
            - database-data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=pgadmi@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - '5050:80'
        restart: always
        volumes: 
            - pgadmin:/root/.pgadmin
volumes:
    database-data:
    pgadmin: