version: '3.9'

services:
    
    postgresql_database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=changeme
            - POSTGRES_DB=goreact
        ports: 
            - "8081:5432"
        restart: always
        volumes: 
            - database-data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=pgadmi@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - '5050:80'
        restart: always
        volumes: 
            - pgadmin:/root/.pgadmin
   
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '4369:4369'
            - '5551:5551'
            - '5552:5552'
            - '5672:5672'
            - '25672:25672'
            - '15672:15672'
        environment:
            - RABBITMQ_SECURE_PASSWORD=yes
            - RABBITMQ_PASSWORD=my_password
        volumes:
             - rabbitmq_data:/bitnami/rabbitmq/mnesia
volumes:
    database-data:
    pgadmin:
    rabbitmq_data:
        driver: local